import Head from "next/head";
import HeroBlock from "../components/HeroBlock/HeroBlock";
import LastWorks from "../components/LastWorks/LastWorks";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <div className="container-global">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeroBlock />
        <LastWorks />

        <div className={styles.bgAnim}>
          <div className={styles.saturnWrapper}>
            <div className={styles.circle}></div>
            <div className={styles.dot}>
              <p>React.js & Next.js</p>
            </div>
          </div>

          <div className={styles.saturnWrapper}>
            <div className={styles.circle}></div>
            <div className={styles.dot}>
              <p>UX/UI</p>
            </div>
          </div>

          <div className={styles.saturnWrapper}>
            <div className={styles.circle}></div>
            <div className={styles.dot}>
              <p>Express.js</p>
            </div>
          </div>
          <div className={styles.saturn}></div>
        </div>
      </div>
    </div>
  );
}
